name: Deploy LindouCV to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet le déploiement manuel

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build web app
        run: flutter build web --release
        
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYTODO_C0F69 }}'
          channelId: live
          projectId: mytodo-c0f69
          
      - name: Deploy success notification
        run: |
          echo "✅ LindouCV déployé avec succès sur Firebase Hosting!"
          echo "🌐 URL: https://mytodo-c0f69.web.app" 