name: Deploy LindouCV to Firebase Hosting (Manual Flutter Setup)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Install Flutter manually
        run: |
          # Download Flutter
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$PATH:`pwd`/flutter/bin"
          
          # Add Flutter to PATH for this session
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          
          # Verify installation
          flutter --version
          flutter doctor
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build web app
        run: flutter build web --release
        
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYTODO_C0F69 }}'
          channelId: live
          projectId: mytodo-c0f69
          
      - name: Deploy success notification
        run: |
          echo "✅ LindouCV déployé avec succès sur Firebase Hosting!"
          echo "🌐 URL: https://mytodo-c0f69.web.app" 