name: Test Flutter Installation

on:
  workflow_dispatch:

jobs:
  test_flutter:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          
      - name: Test Flutter commands
        run: |
          echo "=== Flutter Version ==="
          flutter --version
          
          echo "=== Flutter Doctor ==="
          flutter doctor
          
          echo "=== Flutter Pub Get ==="
          flutter pub get
          
          echo "=== Flutter Build Web ==="
          flutter build web --release
          
          echo "✅ Tous les tests Flutter ont réussi!" 